# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

services:
  cserver:
    image: shd-cserver
    container_name: cserver
    build:
      context: .
      dockerfile: CServer/Dockerfile
    ports:
      - 5020:5020
    networks:
    - app-network

  front:
    image: shd-front
    container_name: front
    build:
      context: .
      dockerfile: FRONT/Dockerfile
    depends_on:
      - cserver
    ports:
      - 5173:5173
    networks:
    - app-network

networks:
  app-network:
